### ISSUE TITLE
[Feat] Ctrl+Z/Ctrl+Y

### ISSUE THREAD

**Issue by chennisden** [OctoPuzzles/octopuzzles#110]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Ctrl+Z and Ctrl+Y do not undo/redo, unlike every other solver.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by starwarigami** [comment]
Should probably make all standard keyboard shortcuts work as expected

Ctrl-Z, Ctrl-Y for Undo/Redo wherever appropriate.
Ctrl-C, Ctrl-X, Ctrl-V in text controls (Comments, notes, walkthroughs - constraint editors?)
Ctrl-A: select all cells in grid, select all text in text controls

Home/End/PgUp/PgDn for navigating around the grid (first and last columns, first and last rows respectively): should also work in all text input controls
