### ISSUE TITLE
Description text not being imported/exported correctly

### ISSUE THREAD

**Issue by starwarigami** [OctoPuzzles/octopuzzles#125]
Octo puzzles uses html markup for new lines, but f-puzzles uses ascii escape characters. Need to convert between the two when importing exporting puzzles.

Probably need to remove all rich text mark up when exporting, I imagine we would have other issues, with italic, bold, etc

**Comment by SorenHolstHansen** [comment]
We could probably just use https://www.npmjs.com/package/html-to-text
